server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
#    active: native
    active: default
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/native-file-repo
        git:
#          uri: file:///Users/kim-daeyoung/git-local-repo
          uri: https://github.com/ethan-kim-backend/spring-cloud-config.git
          username: ethan-kim-backend
          password: eodudrnfl12!@

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
